# Generated by Django 5.0.7 on 2024-07-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usermodel_avatar_alter_usermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='auth_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('VERIFIED', 'VERIFIED'), ('DONE', 'DONE')], default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_role',
            field=models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('SUPERUSER', 'SUPERUSER')], default='USER', max_length=10),
        ),
    ]
