# Generated by Django 5.0.7 on 2024-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_auth_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercodemodel',
            name='expiration_time',
            field=models.DateTimeField(default='2023-02-10'),
            preserve_default=False,
        ),
    ]
