# Generated by Django 5.0.6 on 2024-07-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_category_productsmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamponeyaNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='camponeya_names',
            field=models.ManyToManyField(to='admins.camponeyanames'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='tags',
            field=models.ManyToManyField(to='admins.tags'),
        ),
    ]
