# Generated by Django 5.0.6 on 2024-07-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_camponeyanames_tags_productsmodel_camponeya_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
