# Generated by Django 5.0.6 on 2024-07-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='ategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='admins.category')),
            ],
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.subcategory'),
        ),
    ]
