# Generated by Django 5.0.6 on 2024-07-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_remove_category_parent_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='ategory',
            new_name='category',
        ),
    ]
