# Generated by Django 5.0.6 on 2024-07-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_alter_productsmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admins.subcategory'),
        ),
    ]
