# Generated by Django 5.0.6 on 2024-08-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_remove_productsmodel_camponeya_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admins.category'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='tags',
            field=models.ManyToManyField(null=True, to='admins.tags'),
        ),
    ]
