# Generated by Django 5.0.7 on 2024-07-12 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_productsmodel_price'),
        ('shopping', '0003_cartmodel_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='products',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='products',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='admins.productsmodel'),
            preserve_default=False,
        ),
    ]
