# Generated by Django 5.0.6 on 2024-07-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
