# Generated by Django 5.0.7 on 2024-07-12 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_productsmodel_price'),
        ('shopping', '0006_cheackoutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheackoutmodel',
            name='product',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='admins.productsmodel'),
            preserve_default=False,
        ),
    ]
