# Generated by Django 5.0.7 on 2024-07-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_cheackoutmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheackoutmodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('VERIFYD', 'VERIFYD'), ('ACCEPTED', 'ACCEPTED')], default='NEW', max_length=255),
        ),
    ]
